#!/usr/bin/env bash
# This script configurate enable sites to listen 80 and not 8080 port

sudo sed -i 's/listen 8080/listen 80' /etc/nginx/sites-enabled/default
sudo sed -i 's/8080 default_server ipv6only=on;/80 default_server ipv6only=on;/' /etc/nginx/sites-enabled/default
sudo service nginx restart
