#!/usr/bin/env bash
# fault in Nginx installation from listening on port 80 short and beauty
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
pkill 'nginx'
