#!/usr/bin/env bash
# prints 'Holberton School' x 10

c=1
while [ $c -le 10 ]
do
    if [ $c -eq 4 ]
    then
        echo "bad luck"
    elif [ $c -eq 8 ]
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    let c=c+1
done
