#!/usr/bin/env bash
# edits /etc/hosts file chaging the dns config
cp /etc/hosts ~/new_hdns
sed -i 's/.*localhost/127.0.0.2 localhost/g' ~/new_hdns
echo "8.8.8.8 facebook.com" >> ~/new_hdns
cp -f ~/new_hdns /etc/hosts
