#!/usr/bin/env bash
# restart server process with other user
pkill apache2
sudo chmod 777 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start

